"""Analysis of S-parameter measurement data -- the "Analyse und
Auswertung von Messdaten" and reporting layer on top of raw S11/S21
data (whether that data came from a real Touchstone file or was
generated by this project's transmission-line model)."""

import numpy as np

from src.transmission_line import insertion_loss_db, return_loss_db, vswr


def analyze_sparams(freq_hz, s11, s21=None):
    """Compute the standard derived quantities from raw S-parameters."""
    result = {
        "freq_hz": np.asarray(freq_hz),
        "return_loss_db": return_loss_db(s11),
        "vswr": vswr(s11),
    }
    if s21 is not None:
        result["insertion_loss_db"] = insertion_loss_db(s21)
    return result


def band_summary(analysis, f_low_hz, f_high_hz):
    """Summarize return loss / VSWR / insertion loss within a frequency
    band of interest -- min/max/mean, and the frequency at which the
    worst (minimum) return loss in-band occurs."""
    freq = analysis["freq_hz"]
    in_band = (freq >= f_low_hz) & (freq <= f_high_hz)
    if not np.any(in_band):
        raise ValueError(f"No data points found in band [{f_low_hz}, {f_high_hz}] Hz")

    rl_band = analysis["return_loss_db"][in_band]
    freq_band = freq[in_band]
    worst_idx = int(np.argmin(rl_band))

    summary = {
        "n_points_in_band": int(np.sum(in_band)),
        "return_loss_min_db": float(np.min(rl_band)),
        "return_loss_max_db": float(np.max(rl_band)),
        "return_loss_mean_db": float(np.mean(rl_band)),
        "worst_case_freq_hz": float(freq_band[worst_idx]),
        "vswr_max": float(np.max(analysis["vswr"][in_band])),
    }
    if "insertion_loss_db" in analysis:
        il_band = analysis["insertion_loss_db"][in_band]
        summary["insertion_loss_min_db"] = float(np.min(il_band))
        summary["insertion_loss_max_db"] = float(np.max(il_band))
    return summary


def pass_fail_return_loss(summary, min_return_loss_db):
    """A simple, explicit pass/fail check: does the worst-case in-band
    return loss meet or exceed a minimum acceptable threshold?"""
    passed = summary["return_loss_min_db"] >= min_return_loss_db
    return {
        "passed": bool(passed),
        "threshold_db": min_return_loss_db,
        "worst_case_db": summary["return_loss_min_db"],
        "worst_case_freq_hz": summary["worst_case_freq_hz"],
        "margin_db": summary["return_loss_min_db"] - min_return_loss_db,
    }
