"""A real, spec-compliant Touchstone (.sNp) file reader/writer.

Touchstone is the actual open, industry-standard file format for
RF/microwave S-parameter data (used by every real VNA and RF CAD
tool). This module implements the classic v1.1 format: a `#` option
line (`# HZ S RI R 50`) followed by one data row per frequency point.
Supports 1-port (.s1p) and 2-port (.s2p) files in RI (real/imaginary)
format, which is what this project both writes and reads -- not a
subset invented for convenience, but the exact column ordering the
real spec defines for 2-port data (S11, S21, S12, S22 per row).

No real VNA or lab measurement produced any of this project's .sNp
files -- see the project README. What's real is that this reader/
writer round-trips actual Touchstone-formatted text correctly and
would work unmodified on a file exported by real RF measurement
equipment.
"""

import numpy as np

_FREQ_MULTIPLIERS = {"HZ": 1.0, "KHZ": 1e3, "MHZ": 1e6, "GHZ": 1e9}


def write_touchstone_1port(path, freq_hz, s11, z0=50.0, freq_unit="HZ"):
    """Write a 1-port (.s1p) Touchstone file in RI format."""
    mult = _FREQ_MULTIPLIERS[freq_unit]
    with open(path, "w") as f:
        f.write("! Generated by hf-cable-signal-toolkit\n")
        f.write(f"# {freq_unit} S RI R {z0:g}\n")
        for fr, s in zip(freq_hz, s11):
            f.write(f"{fr / mult:.10g} {s.real:.10g} {s.imag:.10g}\n")


def write_touchstone_2port(path, freq_hz, s11, s21, s12, s22, z0=50.0, freq_unit="HZ"):
    """Write a 2-port (.s2p) Touchstone file in RI format.
    Column order per the real spec: freq, S11, S21, S12, S22."""
    mult = _FREQ_MULTIPLIERS[freq_unit]
    with open(path, "w") as f:
        f.write("! Generated by hf-cable-signal-toolkit\n")
        f.write(f"# {freq_unit} S RI R {z0:g}\n")
        for i, fr in enumerate(freq_hz):
            f.write(
                f"{fr / mult:.10g} "
                f"{s11[i].real:.10g} {s11[i].imag:.10g} "
                f"{s21[i].real:.10g} {s21[i].imag:.10g} "
                f"{s12[i].real:.10g} {s12[i].imag:.10g} "
                f"{s22[i].real:.10g} {s22[i].imag:.10g}\n"
            )


def read_touchstone(path):
    """Read a .s1p or .s2p Touchstone RI-format file.

    Returns a dict with keys: 'freq_hz', 'z0', 'n_ports', and either
    's11' (1-port) or 's11','s21','s12','s22' (2-port), each a complex
    numpy array indexed by frequency point.
    """
    option = None
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("!"):
                continue
            if line.startswith("#"):
                option = line[1:].split()
                continue
            rows.append([float(tok) for tok in line.split()])

    if option is None:
        raise ValueError(f"{path}: no '#' option line found -- not a valid Touchstone file")

    freq_unit = option[0].upper()
    param_type = option[1].upper()
    fmt = option[2].upper()
    z0 = float(option[4]) if len(option) >= 5 else 50.0

    if param_type != "S":
        raise NotImplementedError(f"Only S-parameter files are supported, got '{param_type}'")
    if fmt != "RI":
        raise NotImplementedError(f"Only RI format is supported, got '{fmt}'")

    mult = _FREQ_MULTIPLIERS[freq_unit]
    rows = np.array(rows, dtype=np.float64)
    freq_hz = rows[:, 0] * mult

    n_cols = rows.shape[1] - 1
    if n_cols == 2:
        s11 = rows[:, 1] + 1j * rows[:, 2]
        return {"freq_hz": freq_hz, "z0": z0, "n_ports": 1, "s11": s11}
    elif n_cols == 8:
        s11 = rows[:, 1] + 1j * rows[:, 2]
        s21 = rows[:, 3] + 1j * rows[:, 4]
        s12 = rows[:, 5] + 1j * rows[:, 6]
        s22 = rows[:, 7] + 1j * rows[:, 8]
        return {
            "freq_hz": freq_hz, "z0": z0, "n_ports": 2,
            "s11": s11, "s21": s21, "s12": s12, "s22": s22,
        }
    else:
        raise NotImplementedError(f"Unsupported column count ({n_cols}) -- only 1-port and 2-port RI files are supported")
